name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy file to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: 18.116.19.188
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "index.html"
        target: "/var/www/html/"







